apiVersion: 1

datasources:
  - name: logs-etl
    type: postgres
    access: proxy
    url: DB_URL
    database: neondb
    user: neondb_owner
    secureJsonData:
      password: PASSWORD
    jsonData:
      sslmode: require
      postgresVersion: 1500
      timescaledb: false
